// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgpawogjjifsygcbnyvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpncGF3b2dqamlmc3lnY2JueXZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MDk4MTAsImV4cCI6MjA2NTA4NTgxMH0.fxb5HwbQdOT04odmi7lOPIovxZ02IPqkGjxB9Kx0Cq8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);